// -------------------------------------------------------------
//
// File Name: hdlsrc/distortion/distortion.v
// Created: 2024-11-09 00:34:52
//
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
//
//
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0
// Target subsystem base rate: 0
//
// -------------------------------------------------------------


// -------------------------------------------------------------
//
// Module: distortion
// Source Path: distortion
// Hierarchy Level: 0
// Model version: 1.3
//
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module distortion
  (In1,
   Drive,
   Out1);


    input wire  [15:0] In1;  // uint16
    input wire  [15:0] Drive;  // uint16
    output wire [15:0] Out1;  // uint16

    reg [15:0]         cut_wave = 0;

    always @(*) begin
        if (In1 >= 16'd65534 - Drive)
          cut_wave = 16'd65534 - Drive;
        else if (In1 < 16'd65534 - Drive && In1 > 16'd65534 - 2*Drive)
          cut_wave = 16'd65534 - 2*Drive;
        else cut_wave = In1;
    end
    // assign Out1 = volumn_ctrl_out1;
    assign Out1 = cut_wave;

endmodule  // distortion
